# Changes here will be overwritten by Copier
_commit: 1.5.4
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2019'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: false
project_description: Automatically link across pages in MkDocs.
project_name: mkdocs-autorefs
python_package_command_line_name: ''
python_package_distribution_name: mkdocs-autorefs
python_package_import_name: mkdocs_autorefs
repository_name: autorefs
repository_namespace: mkdocstrings
repository_provider: github.com

